[package]
name = "blender"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]

[dependencies]
blender-derive = { path = "blender-derive" }
byteorder = "1.1.0"
error-chain = "0.11.0"